/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PaymentRouteImport } from './routes/payment'
import { Route as NewsEventsRouteImport } from './routes/news-events'
import { Route as MissionVisionGoalRouteImport } from './routes/mission-vision-goal'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as CoreValuesRouteImport } from './routes/core-values'
import { Route as CooMessageRouteImport } from './routes/coo-message'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CeoMessageRouteImport } from './routes/ceo-message'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as BusinessUnitsRouteImport } from './routes/business-units'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SbuGlobalTechnologyTradeRouteImport } from './routes/sbu.global-technology-trade'
import { Route as SbuDiplomaticTravelSecurityRouteImport } from './routes/sbu.diplomatic-travel-security'
import { Route as SbuAgricultureCommoditiesRouteImport } from './routes/sbu.agriculture-commodities'

const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRoute = PaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsEventsRoute = NewsEventsRouteImport.update({
  id: '/news-events',
  path: '/news-events',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionVisionGoalRoute = MissionVisionGoalRouteImport.update({
  id: '/mission-vision-goal',
  path: '/mission-vision-goal',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const CoreValuesRoute = CoreValuesRouteImport.update({
  id: '/core-values',
  path: '/core-values',
  getParentRoute: () => rootRouteImport,
} as any)
const CooMessageRoute = CooMessageRouteImport.update({
  id: '/coo-message',
  path: '/coo-message',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CeoMessageRoute = CeoMessageRouteImport.update({
  id: '/ceo-message',
  path: '/ceo-message',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessUnitsRoute = BusinessUnitsRouteImport.update({
  id: '/business-units',
  path: '/business-units',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SbuGlobalTechnologyTradeRoute =
  SbuGlobalTechnologyTradeRouteImport.update({
    id: '/sbu/global-technology-trade',
    path: '/sbu/global-technology-trade',
    getParentRoute: () => rootRouteImport,
  } as any)
const SbuDiplomaticTravelSecurityRoute =
  SbuDiplomaticTravelSecurityRouteImport.update({
    id: '/sbu/diplomatic-travel-security',
    path: '/sbu/diplomatic-travel-security',
    getParentRoute: () => rootRouteImport,
  } as any)
const SbuAgricultureCommoditiesRoute =
  SbuAgricultureCommoditiesRouteImport.update({
    id: '/sbu/agriculture-commodities',
    path: '/sbu/agriculture-commodities',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/business-units': typeof BusinessUnitsRoute
  '/careers': typeof CareersRoute
  '/ceo-message': typeof CeoMessageRoute
  '/contact': typeof ContactRoute
  '/coo-message': typeof CooMessageRoute
  '/core-values': typeof CoreValuesRoute
  '/gallery': typeof GalleryRoute
  '/mission-vision-goal': typeof MissionVisionGoalRoute
  '/news-events': typeof NewsEventsRoute
  '/payment': typeof PaymentRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/team': typeof TeamRoute
  '/sbu/agriculture-commodities': typeof SbuAgricultureCommoditiesRoute
  '/sbu/diplomatic-travel-security': typeof SbuDiplomaticTravelSecurityRoute
  '/sbu/global-technology-trade': typeof SbuGlobalTechnologyTradeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/business-units': typeof BusinessUnitsRoute
  '/careers': typeof CareersRoute
  '/ceo-message': typeof CeoMessageRoute
  '/contact': typeof ContactRoute
  '/coo-message': typeof CooMessageRoute
  '/core-values': typeof CoreValuesRoute
  '/gallery': typeof GalleryRoute
  '/mission-vision-goal': typeof MissionVisionGoalRoute
  '/news-events': typeof NewsEventsRoute
  '/payment': typeof PaymentRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/team': typeof TeamRoute
  '/sbu/agriculture-commodities': typeof SbuAgricultureCommoditiesRoute
  '/sbu/diplomatic-travel-security': typeof SbuDiplomaticTravelSecurityRoute
  '/sbu/global-technology-trade': typeof SbuGlobalTechnologyTradeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/business-units': typeof BusinessUnitsRoute
  '/careers': typeof CareersRoute
  '/ceo-message': typeof CeoMessageRoute
  '/contact': typeof ContactRoute
  '/coo-message': typeof CooMessageRoute
  '/core-values': typeof CoreValuesRoute
  '/gallery': typeof GalleryRoute
  '/mission-vision-goal': typeof MissionVisionGoalRoute
  '/news-events': typeof NewsEventsRoute
  '/payment': typeof PaymentRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/team': typeof TeamRoute
  '/sbu/agriculture-commodities': typeof SbuAgricultureCommoditiesRoute
  '/sbu/diplomatic-travel-security': typeof SbuDiplomaticTravelSecurityRoute
  '/sbu/global-technology-trade': typeof SbuGlobalTechnologyTradeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/business-units'
    | '/careers'
    | '/ceo-message'
    | '/contact'
    | '/coo-message'
    | '/core-values'
    | '/gallery'
    | '/mission-vision-goal'
    | '/news-events'
    | '/payment'
    | '/sitemap.xml'
    | '/team'
    | '/sbu/agriculture-commodities'
    | '/sbu/diplomatic-travel-security'
    | '/sbu/global-technology-trade'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/business-units'
    | '/careers'
    | '/ceo-message'
    | '/contact'
    | '/coo-message'
    | '/core-values'
    | '/gallery'
    | '/mission-vision-goal'
    | '/news-events'
    | '/payment'
    | '/sitemap.xml'
    | '/team'
    | '/sbu/agriculture-commodities'
    | '/sbu/diplomatic-travel-security'
    | '/sbu/global-technology-trade'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/business-units'
    | '/careers'
    | '/ceo-message'
    | '/contact'
    | '/coo-message'
    | '/core-values'
    | '/gallery'
    | '/mission-vision-goal'
    | '/news-events'
    | '/payment'
    | '/sitemap.xml'
    | '/team'
    | '/sbu/agriculture-commodities'
    | '/sbu/diplomatic-travel-security'
    | '/sbu/global-technology-trade'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BusinessUnitsRoute: typeof BusinessUnitsRoute
  CareersRoute: typeof CareersRoute
  CeoMessageRoute: typeof CeoMessageRoute
  ContactRoute: typeof ContactRoute
  CooMessageRoute: typeof CooMessageRoute
  CoreValuesRoute: typeof CoreValuesRoute
  GalleryRoute: typeof GalleryRoute
  MissionVisionGoalRoute: typeof MissionVisionGoalRoute
  NewsEventsRoute: typeof NewsEventsRoute
  PaymentRoute: typeof PaymentRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TeamRoute: typeof TeamRoute
  SbuAgricultureCommoditiesRoute: typeof SbuAgricultureCommoditiesRoute
  SbuDiplomaticTravelSecurityRoute: typeof SbuDiplomaticTravelSecurityRoute
  SbuGlobalTechnologyTradeRoute: typeof SbuGlobalTechnologyTradeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news-events': {
      id: '/news-events'
      path: '/news-events'
      fullPath: '/news-events'
      preLoaderRoute: typeof NewsEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mission-vision-goal': {
      id: '/mission-vision-goal'
      path: '/mission-vision-goal'
      fullPath: '/mission-vision-goal'
      preLoaderRoute: typeof MissionVisionGoalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/core-values': {
      id: '/core-values'
      path: '/core-values'
      fullPath: '/core-values'
      preLoaderRoute: typeof CoreValuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coo-message': {
      id: '/coo-message'
      path: '/coo-message'
      fullPath: '/coo-message'
      preLoaderRoute: typeof CooMessageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ceo-message': {
      id: '/ceo-message'
      path: '/ceo-message'
      fullPath: '/ceo-message'
      preLoaderRoute: typeof CeoMessageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-units': {
      id: '/business-units'
      path: '/business-units'
      fullPath: '/business-units'
      preLoaderRoute: typeof BusinessUnitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sbu/global-technology-trade': {
      id: '/sbu/global-technology-trade'
      path: '/sbu/global-technology-trade'
      fullPath: '/sbu/global-technology-trade'
      preLoaderRoute: typeof SbuGlobalTechnologyTradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sbu/diplomatic-travel-security': {
      id: '/sbu/diplomatic-travel-security'
      path: '/sbu/diplomatic-travel-security'
      fullPath: '/sbu/diplomatic-travel-security'
      preLoaderRoute: typeof SbuDiplomaticTravelSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sbu/agriculture-commodities': {
      id: '/sbu/agriculture-commodities'
      path: '/sbu/agriculture-commodities'
      fullPath: '/sbu/agriculture-commodities'
      preLoaderRoute: typeof SbuAgricultureCommoditiesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BusinessUnitsRoute: BusinessUnitsRoute,
  CareersRoute: CareersRoute,
  CeoMessageRoute: CeoMessageRoute,
  ContactRoute: ContactRoute,
  CooMessageRoute: CooMessageRoute,
  CoreValuesRoute: CoreValuesRoute,
  GalleryRoute: GalleryRoute,
  MissionVisionGoalRoute: MissionVisionGoalRoute,
  NewsEventsRoute: NewsEventsRoute,
  PaymentRoute: PaymentRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TeamRoute: TeamRoute,
  SbuAgricultureCommoditiesRoute: SbuAgricultureCommoditiesRoute,
  SbuDiplomaticTravelSecurityRoute: SbuDiplomaticTravelSecurityRoute,
  SbuGlobalTechnologyTradeRoute: SbuGlobalTechnologyTradeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
